### ISSUE TITLE
管理员页面点击用户资料报错

### ISSUE THREAD

**Issue by huisunan** [mingming-cn/redmine_work_wechat#5]
管理员页面点击用户资料报错

<img width="1585" alt="image" src="https://github.com/mingming-cn/redmine_work_wechat/assets/30598579/83e6c1d1-9e95-4de8-8fd1-334601892c26">

<img width="916" alt="image" src="https://github.com/mingming-cn/redmine_work_wechat/assets/30598579/e50bde86-e037-429d-b059-7b3c22d8da46">

**Comment by mingming-cn** [comment]
麻烦看一下服务日志，把对应的报错信息贴一下。

**Comment by huisunan** [comment]
<img width="1053" alt="image" src="https://github.com/mingming-cn/redmine_work_wechat/assets/30598579/ce4c92da-fe02-40cf-bc74-484c3e4ddbca">

**Comment by huisunan** [comment]
有没有debug日志，感觉现在消息都没推送成功

**Comment by mingming-cn** [comment]
> <img alt="image" width="1053" src="https://private-user-images.githubusercontent.com/30598579/345989371-ce4c92da-fe02-40cf-bc74-484c3e4ddbca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDk0ODksIm5iZiI6MTcyMDE0OTE4OSwicGF0aCI6Ii8zMDU5ODU3OS8zNDU5ODkzNzEtY2U0YzkyZGEtZmUwMi00MGNmLWJjNzQtNDg0YzNlNGRkYmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDAzMTMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyM2YyMDNmNTY1YThiM2UwOWZmNDdkNDkwMmU1MTM4YzZlOTk0OTEzYzZlODY2ZTY3NzBkYWI1ODliNjgzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hr0FtLtJI1P23MnVA0GRZs32bnIJSdxCl5ELBLBpLQ0">

在 redmine 根目录下，执行一下数据库迁移命令

```shell
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```

然后重启redmine应该就行了。

**Comment by huisunan** [comment]
我试一下

**Comment by mingming-cn** [comment]
因为长时间没有回复，我先关闭这个issue ，如果有问题可以再开个 issue 反馈问题。
